[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "biofetch"
version = "0.1.0"
description = "Biomedical database search tools"
authors = [{ name = "Behnam Yousefi" }]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "httpx",
]
